### ISSUE TITLE
move this repo to an organization

### ISSUE THREAD

**Issue by srghma** [jmackie/purescript-prettyprinter#2]
I would suggest to create an organization purescript-prettyprinter

and move this repo there as purescript-prettyprinter/purescript-prettyprinter

this would allow us to create other libraries in separate repository like [prettyprinter-ansi-terminal](https://github.com/quchen/prettyprinter/blob/master/prettyprinter-ansi-terminal/README.md)

___ 

P.S. you can add me as an organization member, I plan to use it in https://github.com/purescript-codegen/purescript-ps-cst

**Comment by jmackie** [comment]
More than happy to transfer this to an org, but tbh I don't want to be super involved. Having used this package a little bit, I don't think a strict+barely optimized language like PureScript is a good fit for a Wadler/Leijen pretty printer...

**Comment by srghma** [comment]
@jmackie I have added LazyStream here https://github.com/jmackie/purescript-prettyprinter/pull/3

have no issues with performance

I think I will fork this repo to https://github.com/purescript-codegen/

**Comment by srghma** [comment]
@jmackie would you mind if I fork your repo to https://github.com/purescript-codegen and publish it to http://pursuit.purescript.org/ under name `prettyprinter-renderable`?

**Comment by jmackie** [comment]
More than happy for you to do that - I'll update the README to point at it too :+1:
